### PR TITLE
Added an animated svg logo to the top

### PR DESCRIPTION
**Pull request by tigert**
Added a logo to the top, combined it with the illustration to make it take a bit less space.

image

### CODE REVIEW

**Comment by tigert** [comment]
I am confused about the failing check, as the site seems to work locally without error messages..?

**Comment by mangelajo** [comment]
Sorry, this will fix the error: 
https://github.com/submariner-io/submariner-website/pull/159

hugo was updated and we need to update or hugo-learn-theme, but in the meanwhile I'm pinning hugo to v0.71.0, v0.72.0 breaks

**Comment by tigert** [comment]
Ok, so should I do something on this pull request to make the checks pass? Or is it waiting for the version change still?

**Comment by mangelajo** [comment]
@tigert nice!, sorry I didn't have enough time to look at it.

I feel something off with the colors or composition, although the idea is cool.

Let me try some experiments with the SVG and see what I get.

**Comment by mangelajo** [comment]
image

I propose this change instead
Find a copy of the modified svg:
[frontpage-illustration-logo.zip](https://github.com/submariner-io/submariner-website/files/4736634/frontpage-illustration-logo.zip)

What do you think?

**Comment by Oats87** [comment]
@mangelajo I think your suggestion is great, although for the first thing that someone sees when they browse to the Submariner website I think the logo should be a bit more prominent like it was in the original suggestion. That diagram + logo would be great further down the page IMO, it is possible that this could be changed so the Submariner logo is large and centered (without the animation) at the top, then as you scroll down, you can see your suggested diagram. Just my 2c

**Comment by mangelajo** [comment]
Thanks for your feedback Chris I’ll try and see if I got it and how it looks :+1

Enviado desde mi iPhone

**Comment by mangelajo** [comment]
@Oats87 @tigert @nyechiel  see the alternative here: https://github.com/submariner-io/submariner-website/pull/169 based on comments, not sure if I got it right

**Comment by tigert** [comment]
Ok, I am going to revisit the design, sorry for absence but I have been busy with other things and was on PTO as well. Apologies.

I agree we should put the logo on top. Also, since the current theme is very functional for docs, I am thinking we should maybe create a separate front page that has the side navigation hidden, but rather just links to the most important things (that then have the sidebar). Ideally it could be available through a menu button perhaps (like on mobile sites) but I am not sure my web-fu is strong enough for that, unfortunately.

But the front could then have the logo and the "elevator pitch" on top with an illustration like the pipes graphic. Then below that we could have a few columns with maybe Download, Documentation and Community. We can then write more stuff on those sub pages, but the front page would ideally be something that gets the visitors attention and gets them interested. I will try to get a mockup done, based on the google doc we used for content draft earlier.

**Comment by nyechiel** [comment]
> Ok, I am going to revisit the design, sorry for my absence. I have been busy with other things and was on PTO as well. Apologies.
> 
> I agree we should put the logo on top. Also, since the current theme is very functional for docs, I am thinking we should maybe create a separate front page that has the side navigation hidden, but rather just links to the most important things (that then have the sidebar). Ideally it could be available through a menu button perhaps (like on mobile sites) but I am not sure my web-fu is strong enough for that, unfortunately.
> 
> But the front could then have the logo and the "elevator pitch" on top with an illustration like the pipes graphic. Then below that we could have a few columns with maybe Download, Documentation and Community. We can then write more stuff on those sub pages, but the front page would ideally be something that gets the visitors attention and gets them interested. I will try to get a mockup done, based on the google doc we used for content draft earlier.

Welcome back, @tigert. Thanks for looking at this.. let us know if/how can we help.

**Pull request closed without merging**
