### PR TITLE
Document subctl benchmark verbose flag

### PR DESCRIPTION
**Pull request by maayanf24**
Related to: https://github.com/submariner-io/submariner-operator/issues/748

Signed-off-by: Maayan Friedman <maafried@redhat.com>

### CODE REVIEW

**Review by skitt — APPROVED** [review]

**Comment by tpantelis** [comment]
@skitt @nyechiel  We probably want to hold off on merging this until closer to the release. Perhaps change it to a Draft.

**Comment by nyechiel** [comment]
> @skitt @nyechiel We probably want to hold off on merging this until closer to the release. Perhaps change it to a Draft.

Yeah, I agree that we should wait with the docs part. Maybe it's better to propose a new label, something like "do-not-merge"?

**Comment by tpantelis** [comment]
> > @skitt @nyechiel We probably want to hold off on merging this until closer to the release. Perhaps change it to a Draft.
> 
> Yeah, I agree that we should wait with the docs part. Maybe it's better to propose a new label, something like "do-not-merge"?

I converted it to a Draft - I think that should suffice.

**Comment by skitt** [comment]
> > > @skitt @nyechiel We probably want to hold off on merging this until closer to the release. Perhaps change it to a Draft.
> > 
> > 
> > Yeah, I agree that we should wait with the docs part. Maybe it's better to propose a new label, something like "do-not-merge"?
> 
> I converted it to a Draft - I think that should suffice.

Yup, I don’t think we need a new label for this. I’ve added it to the 0.8.0 project and milestone so we don’t miss it when we wrap up the release.

**Review by dfarrell07 — APPROVED** [review]

**Comment by mangelajo** [comment]
Sorry, now it's conflicting, can you have a look @maayanf24  ?

**Comment by nyechiel** [comment]
Duplicate of https://github.com/submariner-io/submariner-website/pull/363

**Pull request closed without merging**
