### PR TITLE
Modify the `make backport` command to build locally

### PR DESCRIPTION
**Pull request by Jaanki**
following modifications in
https://github.com/submariner-io/shipyard/pull/692

Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Comment by sridhargaddam** [comment]
@aswinsuryan is this working on your host?

**Review by dfarrell07 — APPROVED** [review]

**Comment by aswinsuryan** [comment]
> @aswinsuryan is this working on your host?

@Jaanki @sridhargaddam  tried this and did not work
```
$ make LOCAL_BUILD=1 backport release=release-0.11 pr=1609
Makefile:24: ../shipyard/Makefile.inc: No such file or directory
make: *** No rule to make target '../shipyard/Makefile.inc'.  Stop.
```

**Comment by skitt** [comment]
> > @aswinsuryan is this working on your host?
> 
> @Jaanki @sridhargaddam tried this and did not work
> 
> ```
> $ make LOCAL_BUILD=1 backport release=release-0.11 pr=1609
> Makefile:24: ../shipyard/Makefile.inc: No such file or directory
> make: *** No rule to make target '../shipyard/Makefile.inc'.  Stop.
> ```

You need to have `shipyard` checked out alongside your project.

**Comment by sridhargaddam** [comment]
> You need to have `shipyard` checked out alongside your project.

Thanks @skitt. PR to update the documentation - https://github.com/submariner-io/submariner-website/pull/651

**Pull request merged**
