### PR TITLE
Update Hugo and Learn theme to latest

### PR DESCRIPTION
**Pull request by dfarrell07**
Update both Hugo and the Hugo Learn theme.

See the commit messages for details.

### CODE REVIEW

**Comment by tpantelis** [comment]
bump

**Review by mkolesnik — CHANGES_REQUESTED** [review]
Please be sure to apply any heme hacks we did back to the theme `git log --name-only --pretty=short src/themes/`

**Comment by dfarrell07** [comment]
> Please be sure to apply any heme hacks we did back to the theme `git log --name-only --pretty=short src/themes/`

Thanks! Yeah it's currently broken, I don't remember the issue at this point but I'll look into that once this is a priority again (or someone else can snag this change).

**Comment by dfarrell07** [comment]
I'm going to use this PR as an Issue to track this TODO, basically just adding labels.

**Pull request closed without merging**
