### PR TITLE
Remove Shipyard-specific contributing docs

### PR DESCRIPTION
**Pull request by dfarrell07**
These docs are so detailed, they are very difficult to keep up-to-date
and are not much quicker to understand than just looking at the code.
Given the need for the user to additionally check the code and
differentiate old docs from reality, having the docs creates more work
than they save.

Additionally, the building and testing targets and options are becoming
uniform across all Submariner projects, and therefore are better covered
only once in the general Building and Testing docs.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by tpantelis** [comment]
A lot of this material is related to using shipyard rather than contributing it. After a quick read thru it, I'm not sure we want to drop all of it, eg describing the project structure and how to consume it in another project.  Perhaps we can compromise on the keep up-to-date difficulty and pare down the detail to a basic overview. Also, perhaps this content is better suited for the project page?

**Comment by nyechiel** [comment]
> A lot of this material is related to using shipyard rather than contributing to it. After a quick read thru, I'm not sure we want to drop all of it, eg describing the project structure and how to consume it in another project. Perhaps we can compromise on the keep up-to-date difficulty and pare down the detail to a basic overview. Also, perhaps this content is better suited for the project page?

+1. Mike has put a lot of effort into documenting this info, and I think it is valuable to keep it. I think it makes sense to move this content into the project page itself, as users of Submariner (ideally) should not care about Shipyard, and the content is indeed too detailed for the website.

**Comment by dfarrell07** [comment]
I'm okay with trying to remove the out-of-date parts, reduce it to only the parts that are better understood through docs than just looking at the code, and moving the result somewhere that it doesn't distract uses in the normal-case. My guess is that there would not be much content left after those steps, however. And it seems like we should still go ahead with removing the content here.

**Comment by tpantelis** [comment]
> 
> I don't think we should block this cleanup on re-creating Shipyard docs elsewhere. We can raise an issue with a pointer to this PR, no information will be lost.

yeah but it's just cleanup here - no rush to get this in. Plus there would be some gap in time where no content would be available.  That said, if folks want to push this ahead first then I'm OK.

**Comment by dfarrell07** [comment]
> > I don't think we should block this cleanup on re-creating Shipyard docs elsewhere. We can raise an issue with a pointer to this PR, no information will be lost.
> 
> yeah but it's just cleanup here - no rush to get this in. Plus there would be some gap in time where no content would be available. That said, if folks want to push this ahead first then I'm OK.

But that's kinda my point, that having this version of the content is more harmful than not having it at all. It's a big complication of our UX. I think there's much more rush to clean this up than to have detailed Shipyard docs.

**Comment by dfarrell07** [comment]
This will make another big chunk of these docs out-of-date/unnecessary: https://github.com/submariner-io/shipyard/pull/324

**Comment by tpantelis** [comment]
> > yeah but it's just cleanup here - no rush to get this in. Plus there would be some gap in time where no content would be available. That said, if folks want to push this ahead first then I'm OK.
> 
> But that's kinda my point, that having this version of the content is more harmful than not having it at all. It's a big complication of our UX, and I doubt anyone is finding it useful. I think there's much more rush to clean this up than to have detailed Shipyard docs.

I'm not sure I'd say it's harmful but fair enough.

**Comment by mkolesnik** [comment]
I don't see a problem with moving it but as far as I remember we had a goal to consolidate all the docs on the website.

Additionally a lot of open source projects have both information for developers and for users in the same documentation so I'm not sure this is bad UX.

Obviously it's easier to just remove rather than update the documentation to match the state of the project now :/

**Comment by dfarrell07** [comment]
> I don't see a problem with moving it but as far as I remember we had a goal to consolidate all the docs on the website.

I'm not necessarily recommending it move to the Shipyard repo.

> Additionally a lot of open source projects have both information for developers and for users in the same documentation so I'm not sure this is bad UX.

I'm not proposing the website only have user-focused docs, in fact I've put in a lot of PRs to clean up the contributor-focused docs. It's bad UX because, going through the material, almost all of it is either:

1. Out of date.
2. Too detailed, better just point at/learn from the code(also avoids 1).
3. Too general, already/better covered in the general Building and Testing docs.

And so it's not particularly useful and just adds sources of confusion and distracts from the other docs.

The only exception I see is the section about adding Shipyard to a new project.

> 
> Obviously it's easier to just remove rather than update the documentation to match the state of the project now :/

More than just updating, I think the important part of refactoring these docs would be narrowing their scope and making sure they are all-useful. I don't think most of this still needs docs, and actual devs would be better served with something more focused on what they actually might need to know (how to add Shipyard infra to a project maybe).

**Comment by tpantelis** [comment]
> The only exception I see is the section about adding Shipyard to a new project.

I agree, as I mentioned before,  that the material wrt the project structure and how to consume it seem useful.

**Comment by dfarrell07** [comment]
> > The only exception I see is the section about adding Shipyard to a new project.
> 
> I agree, as I mentioned before, that the material wrt the project structure and how to consume it seem useful.

Refactoring those docs would go well with the effort to add Shipyard support to other (all?) submariner-io/* repos we've discussed a few times. Maybe I should raise an Issue to track that TODO and link to [the (removed) docs](https://github.com/submariner-io/submariner-website/pull/294/files#diff-be3804adb406eaa6bcf3fca3bd97ddc2) to make sure we don't lose them?

**Comment by dfarrell07** [comment]
> > > The only exception I see is the section about adding Shipyard to a new project.
> > 
> > 
> > I agree, as I mentioned before, that the material wrt the project structure and how to consume it seem useful.
> 
> Refactoring those docs would go well with the effort to add Shipyard support to other (all?) submariner-io/* repos we've discussed a few times. Maybe I should raise an Issue to track that TODO and link to [the (removed) docs](https://github.com/submariner-io/submariner-website/pull/294/files#diff-be3804adb406eaa6bcf3fca3bd97ddc2) to make sure we don't lose them?

Raised https://github.com/submariner-io/shipyard/issues/325.

**Comment by mkolesnik** [comment]
I just don't see the point in a "remove it now, rewrite it later (or never)" type of approach if some of the docs are still useful.

We can obviously live without documentation for this area and just have devs copy paste from repos, but since effort was put into documenting it and trying to explain the rationale behind the way it works, it seems weird to me to just throw it all away in hopes of a "docs refactor" sometime later.

**Comment by dfarrell07** [comment]
> I just don't see the point in a "remove it now, rewrite it later (or never)" type of approach if some of the docs are still useful.

As I've said quite a few times, the goal is to improve the website UX by:

1. Not showing users wrong-docs.
2. Not showing users unnecessary/duplicate docs.

**Comment by dfarrell07** [comment]
> We can obviously live without documentation for this area and just have devs copy paste from repos, but since effort was put into documenting it and trying to explain the rationale behind the way it works, it seems weird to me to just throw it all away in hopes of a "docs refactor" sometime later.

This feels a lot like "sunk cost fallacy" reasoning. More docs are not more-better. Just because we have them doesn't mean they add utility overall.

We don't have to wait, but I don't have cycles for https://github.com/submariner-io/shipyard/issues/325 and refactoring out that chunk of docs. Maybe you'd like to work on that @mkolesnik?

**Review by mangelajo — CHANGES_REQUESTED** [review]
Let's try to remove the overlap between https://submariner.io/contributing/building_testing/ && https://submariner.io/contributing/shipyard/   

I think there's useful docs in shipyard, even if they now need a pass and update on the details, but I think most of it is valid.

**Comment by dfarrell07** [comment]
Talking with folks on the Automation sync today, it seems the consensus is to try to refactor this in-place, maybe making it into more of a "How to use shared tooling in new project" guide, but not remove it in the meantime.

**Pull request closed without merging**
