### PR TITLE
Release notes: mention disabling certificate checks

### PR DESCRIPTION
**Pull request by skitt**
This was added in 0.13.0 but missed in the release notes.

Signed-off-by: Stephen Kitt <skitt@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
Maybe we should say what this should be used for?

**Comment by nyechiel** [comment]
Don't we need to include it under a point release (when it becomes available), most likely 0.13.1?

**Comment by skitt** [comment]
> Don't we need to include it under a point release (when it becomes available), most likely 0.13.1?

Yes, that’s why I left the PR as a draft instead of closing it ;-).

**Comment by nyechiel** [comment]
> > Don't we need to include it under a point release (when it becomes available), most likely 0.13.1?
> 
> Yes, that’s why I left the PR as a draft instead of closing it ;-).

Yes, but with this PR you are actually adding the content under 0.13.0.

**Comment by nyechiel** [comment]
> This was added in 0.13.0 but missed in the release notes.
> 
> Signed-off-by: Stephen Kitt [skitt@redhat.com](mailto:skitt@redhat.com)



> This was added in 0.13.0 but missed in the release notes.

@skitt this was not added in 0.13.0 AFAICT: https://github.com/submariner-io/subctl/pull/165

**Comment by nyechiel** [comment]
@skitt this is now mentioned in https://submariner.io/community/releases/#v0131

**Pull request closed without merging**
