### PR TITLE
Add linting to avoid "IPtable"

### PR DESCRIPTION
**Pull request by dfarrell07**
This made it into our release notes recently.

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Review by maayanf24 — APPROVED** [review]

**Review by skitt — APPROVED** [review]
It’s a shame we can’t forbid certain words!

**Review by sridhargaddam — APPROVED** [review]

**Comment by dfarrell07** [comment]
> It’s a shame we can’t forbid certain words!

It might be possible with https://github.com/Trott/remark-lint-prohibited-strings, I'll look into it.

**Comment by maayanf24** [comment]
@dfarrell07 - need a rebase

**Comment by tpantelis** [comment]
@dfarrell07 This needs manual rebase.

**Pull request merged**
