### PR TITLE
Add skeleton for contribution guide (contribution section)

### PR DESCRIPTION
**Pull request by mkolesnik**
This guide outlines the Submariner release process, and how developers
are expected to contribute.

This is merely a skeletal outline which will be filled in following
commits.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

### CODE REVIEW

**Review by maayanf24 — APPROVED** [review]

**Comment by mkolesnik** [comment]
FYI `markdownlinks` fails because of new "contribution" section which obviously isn't published yet, it should go back to normal once the PR merges
If necessary I'll happily add an ignore pattern which we'll have to revert after the merge

**Comment by dfarrell07** [comment]
What's the difference between "Contribution" and "Development"? Isn't "Development" a subset of "Contribution"? 

I think we used to have a Contribution section and merged it with Development because we didn't have an obvious split between the two, were adding confusion about where to find/put things.

I think we should talk about the goal here with a broader set of folks before putting too much more work into this.

**Comment by dfarrell07** [comment]
In general, if we want to do docs structure refactoring, this is the currently-agreed-on goal: https://github.com/submariner-io/enhancements/pull/21

**Comment by mkolesnik** [comment]
> What's the difference between "Contribution" and "Development"? Isn't "Development" a subset of "Contribution"?

As stated in the commit message for the split:
```
    Half the guides in "Development" section are general contribution
    guidelines, it makes sense to split them to their own section.
```

The difference is between guidelines, and detailed guides how to do some things (backport, shipyard, etc).
The first is guidelines to follow, and the second is "how-tos" for specific stuff.
If you have better distinguishable names I don't mind using them.

> 
> I think we used to have a Contribution section and merged it with Development because we didn't have an obvious split between the two, were adding confusion about where to find/put things.

No, there used to be a "Contributing" section which was changed to "For Developers" but it had all this content lumped together.

> 
> I think we should talk about the goal here with a broader set of folks before putting too much more work into this.

This is up for review, there's not "much more" work the split is in the first commit, I don't see why it can't be discussed here.

We're defining general guidelines for working in Submariner, and the ask (which makes a lot of sense) was document it in the website instead of obscure docs.
As part of this work, it made sense to put all guidelines in their own distinguishable section, since youre expected to follow them all, but "Development" section contains content which is not relevant to that.

**Comment by dfarrell07** [comment]
> The first is guidelines to follow

So should the Community Code of Conduct be under that? Getting Help?

It's not clear to me that "Contributing=general guidelines" and "Development=detailed guides".

**Comment by mkolesnik** [comment]
> 
> So should the Community Code of Conduct be under that? Getting Help?

Code of conduct is very general and not relates just to contribution guidelines.

However, "Contributor Roles" definitely does and should move here as well, and part of the "Roadmap" should be here as well (and will be deleted anyway when we flesh out the guidelines).

> 
> It's not clear to me that "Contributing=general guidelines" and "Development=detailed guides".

If you have better names I'm open to suggestions, we can always change names later anyhow but my main point was that these two categories are essentially different groups of content which have been historically (for some or other reason) lumped into one mixed category.

**Comment by maayanf24** [comment]
I prefer the approach of splitting the development process / cycle  from the technical guides of how to do things

**Comment by dfarrell07** [comment]
I'd like to see a proposal for the structure suggestions that can be discussed more widely, and then implement that structure in one change, vs trying to restructure the website for the sake of adding this one section.

**Comment by dfarrell07** [comment]
Ideally, I'd like the enhancement proposal on exactly this topic to get this attention: https://github.com/submariner-io/enhancements/pull/21

**Pull request closed without merging**
