### PR TITLE
Fix broken Docs Style Guide URL

### PR DESCRIPTION
**Pull request by nyechiel**
Signed-off-by: nyechiel <nyechiel@redhat.com>

### CODE REVIEW

**Comment by nyechiel** [comment]
@dfarrell07 any idea why the Links linter is failing here? The current _website/style_guide.md_ results in 404

**Comment by mangelajo** [comment]
The link checker is complaining https://github.com/submariner-io/submariner-website/pull/476/checks?check_run_id=2269638153

**Comment by nyechiel** [comment]
> The link checker is complaining https://github.com/submariner-io/submariner-website/pull/476/checks?check_run_id=2269638153

Indeed, but we are not clear why. I asked Daniel to look into this

**Comment by dfarrell07** [comment]
Sent https://github.com/submariner-io/submariner-website/pull/479 to fix this.

**Pull request closed without merging**
