### PR TITLE
Remove Lighthouse-specific contributing docs

### PR DESCRIPTION
**Pull request by dfarrell07**
Remove Lighthouse-specific contributing docs

These docs are mostly one of the following:

1. Too basic and better left unsaid, like the git docs.
2. Better covered in Submariner-wide docs, like `make e2e` docs.
3. Overly detailed, like the location of components in the dir
   structure.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by tpantelis** [comment]
I agree at least most of this is boilerplate. Also seems inconsistent to have a specific contributing section for one project and not others. One thing though is that the [LH project page](https://github.com/submariner-io/lighthouse) points to this doc so we'll need to clean that up or perhaps link to https://submariner.io/contributing/ as the submariner project page does.

**Comment by dfarrell07** [comment]
/me is also thinking about getting rid of the "Working with Shipyard" docs for similar reasons.

**Comment by nyechiel** [comment]
Agree with @tpantelis. @dfarrell07 can you raise a PR for cleaning https://github.com/submariner-io/lighthouse before we merge this one?

**Comment by dfarrell07** [comment]
@nyechiel @tpantelis Cool, I proposed the LH update in https://github.com/submariner-io/lighthouse/pull/314.

**Review by nyechiel — COMMENTED** [review]
@aswinsuryan, @vthapar do you have any objections for removing this section from the website?

**Review by aswinsuryan — APPROVED** [review]

**Review by nyechiel — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
