### PR TITLE
Stop using `baseurl`, use only `bind`

### PR DESCRIPTION
**Pull request by mkolesnik**
Reason is that baseURL is used for static code generation and has no
real meaning in the context of allowing remote access to the server.

Calrified the docs how to use `BIND` properly.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

### CODE REVIEW

**Review by skitt — CHANGES_REQUESTED** [review]
The base URL might have nothing to do with either the bind address or the bind port, _e.g._ if the Hugo server is exposed behind a different web server, or is run inside a container with its bind port exposed on a different port.

**Comment by mkolesnik** [comment]
> The base URL might have nothing to do with either the bind address or the bind port, _e.g._ if the Hugo server is exposed behind a different web server, or is run inside a container with its bind port exposed on a different port.

For devel testing purposes it doesnt make sense, e.g you wouldnt be running `make server` and then bothering to set up a proxy in front of it just for the same of 5-10 minutes of testing the website thats generated.

Regardless, the page links all keep generating with whatever IP you used to access with, so if youre using `localhost` all local links point to `http://localhost/..` and if you used e.g. `192.168.2.10` then the links would be `http://192.168.2.10/..`.
Base URL has almost no meaning when run in this mode (AFAICT it basically affects what the server prints when its run, but nothing in the actual generated content)

**Comment by skitt** [comment]
> > The base URL might have nothing to do with either the bind address or the bind port, _e.g._ if the Hugo server is exposed behind a different web server, or is run inside a container with its bind port exposed on a different port.
> 
> For devel testing purposes it doesnt make sense, e.g you wouldnt be running `make server` and then bothering to set up a proxy in front of it just for the same of 5-10 minutes of testing the website thats generated.

Kindly refer to the PR which started all this: https://github.com/submariner-io/submariner-website/pull/694. It might not make sense to you, but it does make enough sense to others that they submitted a PR to support the use case.

> Regardless, the page links all keep generating with whatever IP you used to access with, so if youre using `localhost` all local links point to `http://localhost/..` and if you used e.g. `192.168.2.10` then the links would be `http://192.168.2.10/..`. Base URL has almost no meaning when run in this mode (AFAICT it basically affects what the server prints when its run, but nothing in the actual generated content)

No, the page links are generated using whatever base URL is specified when starting the server. [Hugo server](https://gohugo.io/commands/hugo_server/) doesn’t serve the generated content from disk, it generates it in memory (and updates it whenever the source files change).

Here’s an example, running on my laptop, with links which don’t refer to localhost:

Screenshot from 2022-03-08 10-35-13

**Comment by mkolesnik** [comment]
> > Regardless, the page links all keep generating with whatever IP you used to access with, so if youre using `localhost` all local links point to `http://localhost/..` and if you used e.g. `192.168.2.10` then the links would be `http://192.168.2.10/..`. Base URL has almost no meaning when run in this mode (AFAICT it basically affects what the server prints when its run, but nothing in the actual generated content)
> 
> No, the page links are generated using whatever base URL is specified when starting the server. [Hugo server](https://gohugo.io/commands/hugo_server/) doesn’t serve the generated content from disk, it generates it in memory (and updates it whenever the source files change).
> 
> Here’s an example, running on my laptop, with links which don’t refer to localhost:
> 
> [snip]

That's what I said, the links are dynamic based on where you access it. For example I run with `baseURL=http://bubu`:
```bash
./hugo server -w -s src --bind=0.0.0.0 --port=1314 --baseURL=http://bubu

                   | EN   
-------------------+------
  Pages            | 116  
  Paginator pages  |   0  
  Non-page files   |   1  
  Static files     | 101  
  Processed images |   0  
  Aliases          |   0  
  Sitemaps         |   1  
  Cleaned          |   0  

Built in 196 ms
Watching for changes in /home/mkolesni/submariner-website/src/{archetypes,content,layouts,static,themes}
Watching for config changes in src/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://bubu:1314/ (bind address 0.0.0.0)
Press Ctrl+C to stop
```

And I'm getting the following content:
image

If I access it via localhost then it'll use `http://locaslhost` as the base of the links.

Also looking at the HTML clearly reveals the links to be relative:
```html
<a href="./getting-started/architecture/service-discovery/" class="highlight">Service Discovery</a>
```

Have you tried this patch with you setup and see that it doesnt work as expected?

**Review by skitt — APPROVED** [review]
OK, thanks for the explanations, I’d missed the use of “relative” URLs. For me this only fails in scenarios behind a web server, and since this is only intended for development...

**Review by mkimuram — APPROVED** [review]
@mkolesnik Thank your for your improvement. Approved.

**Pull request merged**
